class server_alerts:
    alert_notifi_locator=('xpath','//h1[text()="Alert and Notification"]')
    alert_btn=('xpath','//button[contains(text(),"Create Alert")]')
    type_loc=('xpath','//select[@formcontrolname="alertType_prop"]')
    server_loc=('xpath','//select[@formcontrolname="serverId"]')
    application_loc=('xpath','//select[@formcontrolname="applicationName"]')

    alertname_loc=('xpath','//input[@formcontrolname="alertName"]')
    triggercount_loc=('xpath','//input[@formcontrolname="triggerCount"]')
    alertprop_loc=('xpath','//select[@formcontrolname="alertName_prop"]')
    threshold_loc=('xpath','//input[@formcontrolname="threshold"]')
    evalution_period=('xpath','//select[@formcontrolname="evaluationPeriod_prop"]')
    alert_appname_loc=('xpath','//input[@formcontrolname="app_name"]')
    latency_bucket_loc=('xpath','//input[@formcontrolname="latency_bucket"]')
    api_path_loc=('xpath','//input[@formcontrolname="apiPath"]')
    status_code=('xpath','//input[@formcontrolname="statusCode"]')

    severity_loc=('xpath','//select[@formcontrolname="severity"]')
    category_loc=('xpath','//select[@formcontrolname="category"]')
    emailreceiptents_loc=('xpath','//input[@formcontrolname="emailRecipients"]')
    phonenumbers_loc=('xpath','//input[@formcontrolname="phoneNumbers"]')
    alert_accept=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Create Alert")]')
    alert_cancel=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Cancel")]')
    add_alert=('xpath','//button[contains(text(),"Add Alert") and @type="button"]')


class API_alerts:
    alert_notifi_locator=('xpath','//h1[text()="Alert and Notification"]')
    api_alert_loc=('xpath','//span[text()="API"]')
    alert_btn=('xpath','//button[contains(text(),"Create Alert")]')
    api_url=('xpath','//input[@formcontrolname="apiUrl"]')
    api_alert_key=('xpath','//label[text()="Key"]/following-sibling::input[contains(@placeholder,"response.code")]')
    api_alert_value=('xpath','//label[text()="Value"]/following-sibling::input[contains(@placeholder,"400")]')
    api_alert_unit=('xpath','//label[text()="Unit"]/following-sibling::input[contains(@placeholder,"ms")]')
    add_property=('xpath','//button[@title="Add Alert Property"]')
    delete_property=('xpath','//button[@title="Remove Alert Property"]')
    optional_settings=('xpath','//span[text()="Optional Settings"]/following-sibling::span[@class="toggle-icon"]')
    eval_frequency=('xpath','//select[@formcontrolname="evaluationFrequency"]')
    enable_immediatly=('xpath','//label[text()="Enable Immediately"]/following-sibling::div[@class="toggle-switch"]/label[@for="enableImmediately"]/span[@class="toggle-slider"]')
    emailreceiptents_loc=('xpath','//input[@formcontrolname="emailRecipients"]')
    phonenumbers_loc=('xpath','//input[@formcontrolname="phoneNumbers"]')
    message_loc=('xpath','//textarea[@formcontrolname="customMessage"]')
    save_config=('xpath','//div[@class="modal-footer"]/button[contains(text(),"Save Configuration") and @type="submit"]')
    cancel_config=('xpath','//div[@class="modal-footer"]/button[contains(text(),"Cancel") and @type="button"]')
    add_alert = ('xpath', '//button[contains(text(),"Add Alert") and @type="button"]')

class application_alerts:
    alert_notifi_locator=('xpath','//h1[text()="Alert and Notification"]')
    application_feature=('xpath','//span[text()="Application"]')
    alert_btn=('xpath','//button[contains(text(),"Create Alert")]')
    type_loc=('xpath','//select[@formcontrolname="alertType_prop"]')
    server_loc=('xpath','//select[@formcontrolname="serverId"]')
    application_loc=('xpath','//select[@formcontrolname="applicationName"]')

    alertname_loc=('xpath','//input[@formcontrolname="alertName"]')
    triggercount_loc=('xpath','//input[@formcontrolname="triggerCount"]')
    alertprop_loc=('xpath','//select[@formcontrolname="alertName_prop"]')
    threshold_loc=('xpath','//input[@formcontrolname="threshold"]')
    evalution_period=('xpath','//select[@formcontrolname="evaluationPeriod_prop"]')
    alert_appname_loc=('xpath','//input[@formcontrolname="app_name"]')
    latency_bucket_loc=('xpath','//input[@formcontrolname="latency_bucket"]')
    api_path_loc=('xpath','//input[@formcontrolname="apiPath"]')
    status_code=('xpath','//input[@formcontrolname="statusCode"]')

    severity_loc=('xpath','//select[@formcontrolname="severity"]')
    category_loc=('xpath','//select[@formcontrolname="category"]')
    emailreceiptents_loc=('xpath','//input[@formcontrolname="emailRecipients"]')
    phonenumbers_loc=('xpath','//input[@formcontrolname="phoneNumbers"]')
    alert_accept=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Create Alert")]')
    alert_cancel=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Cancel")]')
    add_alert=('xpath','//button[contains(text(),"Add Alert")]')

class alert_rules:
    alert_notifi_locator=('xpath','//h1[text()="Alert and Notification"]')
    alert_rules_feature=('xpath','//span[text()="Alert Rules"]')
    alert_btn=('xpath','//button[contains(text(),"Create Alert")]')
    type_loc=('xpath','//select[@formcontrolname="alertType_prop"]')
    server_loc=('xpath','//select[@formcontrolname="serverId"]')
    application_loc=('xpath','//select[@formcontrolname="applicationName"]')

    alertname_loc=('xpath','//input[@formcontrolname="alertName"]')
    triggercount_loc=('xpath','//input[@formcontrolname="triggerCount"]')
    alertprop_loc=('xpath','//select[@formcontrolname="alertName_prop"]')
    threshold_loc=('xpath','//input[@formcontrolname="threshold"]')
    evalution_period=('xpath','//select[@formcontrolname="evaluationPeriod_prop"]')
    alert_appname_loc=('xpath','//input[@formcontrolname="app_name"]')
    latency_bucket_loc=('xpath','//input[@formcontrolname="latency_bucket"]')
    api_path_loc=('xpath','//input[@formcontrolname="apiPath"]')
    status_code=('xpath','//input[@formcontrolname="statusCode"]')

    severity_loc=('xpath','//select[@formcontrolname="severity"]')
    category_loc=('xpath','//select[@formcontrolname="category"]')
    emailreceiptents_loc=('xpath','//input[@formcontrolname="emailRecipients"]')
    phonenumbers_loc=('xpath','//input[@formcontrolname="phoneNumbers"]')
    alert_accept=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Create Alert")]')
    alert_cancel=('xpath','//div[@class="modal-footer"]/child::button[contains(text(),"Cancel")]')
    add_alert=('xpath','//button[contains(text(),"Add Alert")]')




